bedroom_choices = {
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
    '6': 6,
    '7': 7,
    '8': 8,
    '9': 9,
    '10': 10
}

price_choices = {
    '10000': '$100,00',
    '20000': '$200,00',
    '30000': '$300,00',
    '40000': '$400,00',
    '50000': '$500,00',
    '60000': '$600,00',
    '70000': '$700,00',
    '80000': '$800,00',
    '90000': '$900,00',
    '100000': '$1M+'
}

state_choices = {
    "AL": 'Alabama',
    "AK": 'Alaska',
    "AZ": 'Arizona',
    "AR": 'Arkansas',
    "CA": 'California',
    "CO": 'Colorado',
    "CT": 'Connecticut',
    "DE": 'Delaware',
    "DC": 'District Of Columbia',
    "FL": 'Florida',
    "GA": 'Georgia',
    "HI": 'Hawaii',
    "ID": 'Idaho',
    "IL": 'Illinois',
    "IN": 'Indiana',
    "IA": 'Iowa',
    "KS": 'Kansas',
    "KY": 'Kentucky',
    "LA": 'Louisiana',
    "ME": 'Maine',
    "MD": 'Maryland',
    "MA": 'Massachusetts',
    "MI": 'Michigan',
    "MN": 'Minnesota',
    "MS": 'Mississippi',
    "MO": 'Missouri',
    "MT": 'Montana',
    "NE": 'Nebraska',
    "NV": 'Nevada',
    "NH": 'New Hampshire',
    "NJ": 'New Jersey',
    "NM": 'New Mexico',
    "NY": 'New York',
    "NC": 'North Carolina',
    "ND": 'North Dakota',
    "OH": 'Ohio',
    "OK": 'Oklahoma',
    "OR": 'Oregon',
    "PA": 'Pennsylvania',
    "RI": 'Rhode Island',
    "SC": 'South Carolina',
    "SD": 'South Dakota',
    "TN": 'Tennessee',
    "TX": 'Texas',
    "UT": 'Utah',
    "VT": 'Vermont',
    "VA": 'Virginia',
    "WA": 'Washington',
    "WV": 'West Virginia',
    "WI": 'Wisconsin',
    "WY": 'Wyoming',
}
