# Generated by Django 2.2.6 on 2019-10-20 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 20, 16, 15, 57, 900098)),
        ),
    ]
