# Generated by Django 2.2.6 on 2019-10-20 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20191020_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 20, 16, 18, 10, 197785)),
        ),
    ]
